-- 테이블명세서_임채현.pdf(2026-09-26 받음)에 있고 공용 DB 에 아직 없는 테이블 11개를 만듭니다.
-- CREATE TABLE 문은 명세서 그대로 옮기고 IF NOT EXISTS 만 붙였습니다.
-- 명세서와 다른 곳은 한 군데입니다: TB_SMS_SEND_HISTORY 의 CK_SMS_SEND_STATUS 뒤에 빠진 쉼표를 넣었습니다(없으면 문법 오류).
-- 기존 테이블 4개(TB_HOSPITAL, TB_WARD, TB_EMP, TB_ADMIN_HISTORY)는 바꾸지 않습니다.
-- 이전 파일 20260925_detection_event_tables.sql(9개)은 그대로 두었습니다. 이 파일이 그 9개 + TB_CAREGIVER, TB_EVENT_MEDIA 입니다.
--
-- 전부 한 트랜잭션입니다. 중간에 하나라도 실패하면 아무것도 만들어지지 않습니다.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '30s';
SET LOCAL search_path = public;

-- 시작 전 확인: 만들 테이블이 이미 있으면 멈춘다(모양이 다른 테이블을 조용히 건너뛰지 않게).
DO $$
DECLARE
    existing TEXT;
BEGIN
    SELECT string_agg(table_name, ', ') INTO existing
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name IN ('tb_location', 'tb_caregiver', 'tb_edge_device', 'tb_camera', 'tb_camera_config',
                         'tb_model_bundle', 'tb_camera_session', 'tb_detection_event', 'tb_event_action',
                         'tb_sms_send_history', 'tb_event_media');
    IF existing IS NOT NULL THEN
        RAISE EXCEPTION '이미 있는 테이블이 있어 멈춥니다: %', existing;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS TB_LOCATION (
    LOCATION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WARD_ID BIGINT NOT NULL,
    LOCATION_NM VARCHAR(100) NOT NULL,
    LOCATION_TYPE VARCHAR(20) NOT NULL,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_LOCATION_WARD
        FOREIGN KEY (WARD_ID)
        REFERENCES TB_WARD(WARD_ID)
        ON DELETE RESTRICT,
    CONSTRAINT UK_LOCATION_WARD_NM
        UNIQUE (WARD_ID, LOCATION_NM),
    CONSTRAINT CK_LOCATION_NM
        CHECK (BTRIM(LOCATION_NM) <> ''),
    CONSTRAINT CK_LOCATION_TYPE
        CHECK (LOCATION_TYPE IN ('ROOM', 'COMMON'))
);

CREATE TABLE IF NOT EXISTS TB_CAREGIVER (
    CAREGIVER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARE_NM VARCHAR(20) NOT NULL,
    HOSP_DIV_ID VARCHAR(30) NOT NULL,
    LOCATION_ID BIGINT NOT NULL,
    PHONE_NO VARCHAR(20) NOT NULL,
    USE_YN CHAR(1) NOT NULL,
    CRT_DT TIMESTAMPTZ NOT NULL,
    UPD_DT TIMESTAMPTZ NOT NULL,
    CONSTRAINT FK_CAREGIVER_HOSPITAL
        FOREIGN KEY (HOSP_DIV_ID)
        REFERENCES TB_HOSPITAL(HOSP_DIV_ID),
    CONSTRAINT FK_CAREGIVER_LOCATION
        FOREIGN KEY (LOCATION_ID)
        REFERENCES TB_LOCATION(LOCATION_ID),
    CONSTRAINT CK_CAREGIVER_USE_YN
        CHECK (USE_YN IN ('Y', 'N'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UK_CAREGIVER_ACTIVE_LOCATION
    ON TB_CAREGIVER (LOCATION_ID)
    WHERE USE_YN = 'Y';

CREATE TABLE IF NOT EXISTS TB_EDGE_DEVICE (
    EDGE_DEVICE_ID BIGINT
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    HOSP_DIV_ID VARCHAR(30) NOT NULL,
    DEVICE_NM VARCHAR(100) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_SEEN_AT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPD_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_EDGE_DEVICE_HOSPITAL
        FOREIGN KEY (HOSP_DIV_ID)
        REFERENCES TB_HOSPITAL(HOSP_DIV_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_EDGE_DEVICE_NM
        CHECK (BTRIM(DEVICE_NM) <> '')
);

CREATE TABLE IF NOT EXISTS TB_CAMERA (
    CAMERA_ID BIGINT
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    EDGE_DEVICE_ID BIGINT NOT NULL,
    LOCATION_ID BIGINT NOT NULL,
    SOURCE_REF TEXT NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_FRAME_AT TIMESTAMPTZ,
    LAST_INFER_AT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPD_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_CAMERA_EDGE_DEVICE
        FOREIGN KEY (EDGE_DEVICE_ID)
        REFERENCES TB_EDGE_DEVICE(EDGE_DEVICE_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_CAMERA_LOCATION
        FOREIGN KEY (LOCATION_ID)
        REFERENCES TB_LOCATION(LOCATION_ID)
        ON DELETE RESTRICT,
    CONSTRAINT UK_CAMERA_SOURCE
        UNIQUE (EDGE_DEVICE_ID, SOURCE_REF),
    CONSTRAINT CK_CAMERA_SOURCE_REF
        CHECK (BTRIM(SOURCE_REF) <> '')
);

CREATE TABLE IF NOT EXISTS TB_CAMERA_CONFIG (
    CAMERA_ID BIGINT NOT NULL,
    CONFIG_VER INTEGER NOT NULL,
    CAPTURE_CONFIG JSONB NOT NULL,
    BED_ROI JSONB,
    BED_EXIT_CONFIG JSONB,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CAMERA_CONFIG
        PRIMARY KEY (CAMERA_ID, CONFIG_VER),
    CONSTRAINT FK_CAMERA_CONFIG_CAMERA
        FOREIGN KEY (CAMERA_ID)
        REFERENCES TB_CAMERA(CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_CAMERA_CONFIG_VER
        CHECK (CONFIG_VER > 0),
    CONSTRAINT CK_CAMERA_CAPTURE_CONFIG
        CHECK (JSONB_TYPEOF(CAPTURE_CONFIG) = 'object'),
    CONSTRAINT CK_CAMERA_BED_ROI
        CHECK (
            BED_ROI IS NULL
            OR JSONB_TYPEOF(BED_ROI) = 'object'
        ),
    CONSTRAINT CK_CAMERA_BED_EXIT_CONFIG
        CHECK (
            BED_EXIT_CONFIG IS NULL
            OR JSONB_TYPEOF(BED_EXIT_CONFIG) = 'object'
        ),
    CONSTRAINT CK_CAMERA_BED_CONFIG_PAIR
        CHECK (
            (BED_ROI IS NULL AND BED_EXIT_CONFIG IS NULL)
            OR
            (BED_ROI IS NOT NULL AND BED_EXIT_CONFIG IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS TB_MODEL_BUNDLE (
    MODEL_BUNDLE_ID BIGINT
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    BUNDLE_NM VARCHAR(100) NOT NULL,
    POSE_MODEL_NM VARCHAR(150) NOT NULL,
    POSE_MODEL_SHA256 CHAR(64) NOT NULL,
    FALL_MODEL_NM VARCHAR(150) NOT NULL,
    FALL_MODEL_SHA256 CHAR(64) NOT NULL,
    FEATURE_VER VARCHAR(50) NOT NULL,
    MODEL_CONFIG JSONB
        NOT NULL
        DEFAULT '{}'::JSONB,
    CRT_DT TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),
    CONSTRAINT UK_MODEL_BUNDLE_NM
        UNIQUE (BUNDLE_NM),
    CONSTRAINT CK_MODEL_BUNDLE_NM
        CHECK (BTRIM(BUNDLE_NM) <> ''),
    CONSTRAINT CK_POSE_MODEL_NM
        CHECK (BTRIM(POSE_MODEL_NM) <> ''),
    CONSTRAINT CK_FALL_MODEL_NM
        CHECK (BTRIM(FALL_MODEL_NM) <> ''),
    CONSTRAINT CK_FEATURE_VER
        CHECK (BTRIM(FEATURE_VER) <> ''),
    CONSTRAINT CK_POSE_MODEL_SHA256
        CHECK (POSE_MODEL_SHA256 ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT CK_FALL_MODEL_SHA256
        CHECK (FALL_MODEL_SHA256 ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT CK_MODEL_CONFIG
        CHECK (JSONB_TYPEOF(MODEL_CONFIG) = 'object')
);

CREATE TABLE IF NOT EXISTS TB_CAMERA_SESSION (
    CAMERA_SESSION_ID UUID PRIMARY KEY,
    CAMERA_ID BIGINT NOT NULL,
    MODEL_BUNDLE_ID BIGINT NOT NULL,
    CONFIG_VER INTEGER NOT NULL,
    STARTED_AT TIMESTAMPTZ NOT NULL,
    ENDED_AT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_CAMERA_SESSION_CAMERA
        FOREIGN KEY (CAMERA_ID)
        REFERENCES TB_CAMERA(CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_CAMERA_SESSION_MODEL
        FOREIGN KEY (MODEL_BUNDLE_ID)
        REFERENCES TB_MODEL_BUNDLE(MODEL_BUNDLE_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_CAMERA_SESSION_CONFIG
        FOREIGN KEY (CAMERA_ID, CONFIG_VER)
        REFERENCES TB_CAMERA_CONFIG(CAMERA_ID, CONFIG_VER)
        ON DELETE RESTRICT,
    CONSTRAINT UK_CAMERA_SESSION_CAMERA
        UNIQUE (CAMERA_SESSION_ID, CAMERA_ID),
    CONSTRAINT CK_CAMERA_SESSION_CONFIG_VER
        CHECK (CONFIG_VER > 0),
    CONSTRAINT CK_CAMERA_SESSION_TIME
        CHECK (
            ENDED_AT IS NULL
            OR ENDED_AT > STARTED_AT
        )
);

CREATE TABLE IF NOT EXISTS TB_DETECTION_EVENT (
    EVENT_ID UUID PRIMARY KEY,
    CAMERA_ID BIGINT NOT NULL,
    CAMERA_SESSION_ID UUID NOT NULL,
    LOCATION_ID BIGINT NOT NULL,
    TRACK_ID INTEGER,
    EVENT_TYPE VARCHAR(20) NOT NULL,
    DECISION_ST VARCHAR(10) NOT NULL,
    EVENT_AT TIMESTAMPTZ NOT NULL,
    DECISION_SCORE DOUBLE PRECISION,
    EVENT_DETAIL JSONB
        NOT NULL
        DEFAULT '{}'::JSONB,
    CRT_DT TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),
    CONSTRAINT FK_DETECTION_EVENT_CAMERA
        FOREIGN KEY (CAMERA_ID)
        REFERENCES TB_CAMERA(CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_DETECTION_EVENT_LOCATION
        FOREIGN KEY (LOCATION_ID)
        REFERENCES TB_LOCATION(LOCATION_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_DETECTION_EVENT_SESSION
        FOREIGN KEY (CAMERA_SESSION_ID, CAMERA_ID)
        REFERENCES TB_CAMERA_SESSION(CAMERA_SESSION_ID, CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_DETECTION_EVENT_DECISION
        CHECK (
            (
                EVENT_TYPE = 'FALL'
                AND DECISION_ST IN ('CONFIRMED', 'SUSPECTED')
            )
            OR
            (
                EVENT_TYPE = 'BED_EXIT'
                AND DECISION_ST = 'CONFIRMED'
            )
        ),
    CONSTRAINT CK_DETECTION_TRACK_ID
        CHECK (
            TRACK_ID IS NULL
            OR TRACK_ID >= 0
        ),
    CONSTRAINT CK_DETECTION_EVENT_DETAIL
        CHECK (
            JSONB_TYPEOF(EVENT_DETAIL) = 'object'
        )
);

CREATE TABLE IF NOT EXISTS TB_EVENT_ACTION (
    ACTION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_ID UUID NOT NULL,
    HANDLER_ID VARCHAR(20) NOT NULL,
    PATIENT_NM VARCHAR(50) NOT NULL,
    ACTION_CONTENT VARCHAR(1000) NOT NULL,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_EVENT_ACTION_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES TB_DETECTION_EVENT(EVENT_ID),
    CONSTRAINT FK_EVENT_ACTION_HANDLER
        FOREIGN KEY (HANDLER_ID)
        REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT UK_EVENT_ACTION_EVENT
        UNIQUE (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS TB_SMS_SEND_HISTORY (
    SMS_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_ID UUID NOT NULL,
    USER_TYPE VARCHAR(10) NOT NULL,
    USER_ID VARCHAR(20) NOT NULL,
    PHONE_NO VARCHAR(20) NOT NULL,
    MESSAGE_CONTENT VARCHAR(500) NOT NULL,
    SEND_STATUS VARCHAR(10) NOT NULL,
    SEND_DT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_SMS_SEND_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES TB_DETECTION_EVENT(EVENT_ID),
    CONSTRAINT CK_SMS_SEND_USER_TYPE
        CHECK (USER_TYPE IN ('EMP', 'CAREGIVER')),
    CONSTRAINT CK_SMS_SEND_STATUS
        CHECK (SEND_STATUS IN ('SUCCESS', 'FAILED')),
    CONSTRAINT UK_SMS_SEND_EVENT_RECIPIENT
        UNIQUE (EVENT_ID, USER_TYPE, USER_ID)
);

CREATE TABLE IF NOT EXISTS TB_EVENT_MEDIA (
    EVENT_ID UUID PRIMARY KEY,
    STORAGE_URI TEXT,
    MEDIA_ST VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',
    CLIP_START_AT TIMESTAMPTZ,
    CLIP_END_AT TIMESTAMPTZ,
    SIZE_BYTES BIGINT,
    CRT_DT TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),
    UPD_DT TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),
    CONSTRAINT FK_EVENT_MEDIA_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES TB_DETECTION_EVENT(EVENT_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_EVENT_MEDIA_ST
        CHECK (
            MEDIA_ST IN (
                'PENDING',
                'READY',
                'FAILED'
            )
        ),
    CONSTRAINT CK_EVENT_MEDIA_URI
        CHECK (
            STORAGE_URI IS NULL
            OR BTRIM(STORAGE_URI) <> ''
        ),
    CONSTRAINT CK_EVENT_MEDIA_READY_URI
        CHECK (
            MEDIA_ST <> 'READY'
            OR (
                STORAGE_URI IS NOT NULL
                AND BTRIM(STORAGE_URI) <> ''
            )
        ),
    CONSTRAINT CK_EVENT_MEDIA_TIME
        CHECK (
            CLIP_START_AT IS NULL
            OR CLIP_END_AT IS NULL
            OR CLIP_END_AT > CLIP_START_AT
        ),
    CONSTRAINT CK_EVENT_MEDIA_SIZE
        CHECK (
            SIZE_BYTES IS NULL
            OR SIZE_BYTES >= 0
        )
);

-- 끝나기 전 확인: 11개가 모두 있어야 저장한다.
DO $$
DECLARE
    made INTEGER;
BEGIN
    SELECT count(*) INTO made
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name IN ('tb_location', 'tb_caregiver', 'tb_edge_device', 'tb_camera', 'tb_camera_config',
                         'tb_model_bundle', 'tb_camera_session', 'tb_detection_event', 'tb_event_action',
                         'tb_sms_send_history', 'tb_event_media');
    IF made <> 11 THEN
        RAISE EXCEPTION '테이블이 11개가 아니라 %개라서 되돌립니다.', made;
    END IF;
END $$;

COMMIT;
